/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as StopsIndexImport } from './routes/stops/index'
import { Route as BusRoutesIndexImport } from './routes/bus-routes/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StopsIndexRoute = StopsIndexImport.update({
  id: '/stops/',
  path: '/stops/',
  getParentRoute: () => rootRoute,
} as any)

const BusRoutesIndexRoute = BusRoutesIndexImport.update({
  id: '/bus-routes/',
  path: '/bus-routes/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bus-routes/': {
      id: '/bus-routes/'
      path: '/bus-routes'
      fullPath: '/bus-routes'
      preLoaderRoute: typeof BusRoutesIndexImport
      parentRoute: typeof rootRoute
    }
    '/stops/': {
      id: '/stops/'
      path: '/stops'
      fullPath: '/stops'
      preLoaderRoute: typeof StopsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bus-routes': typeof BusRoutesIndexRoute
  '/stops': typeof StopsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bus-routes': typeof BusRoutesIndexRoute
  '/stops': typeof StopsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bus-routes/': typeof BusRoutesIndexRoute
  '/stops/': typeof StopsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bus-routes' | '/stops'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bus-routes' | '/stops'
  id: '__root__' | '/' | '/bus-routes/' | '/stops/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusRoutesIndexRoute: typeof BusRoutesIndexRoute
  StopsIndexRoute: typeof StopsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusRoutesIndexRoute: BusRoutesIndexRoute,
  StopsIndexRoute: StopsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bus-routes/",
        "/stops/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bus-routes/": {
      "filePath": "bus-routes/index.tsx"
    },
    "/stops/": {
      "filePath": "stops/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
